name: shellcheck
on:
  push:
  schedule:
    - cron: '4 4 1 * *'
jobs:
  run_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: style
