name: shellcheck
on:
  push:
jobs:
  run_shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: run shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: style
